export const PROVIDER_NAMES: Record<string, string> = {
  cc: "Claude Code",
  cx: "OpenAI Codex",
  gc: "Gemini CLI",
  qw: "Qwen Code",
  if: "iFlow AI",
  ag: "Antigravity",
  gh: "GitHub Copilot",
  kr: "Kiro AI",
  cu: "Cursor IDE",
  kc: "KiloCode",
  cl: "Cline",
  kmc: "Kimi Coding",
  openai: "OpenAI",
  anthropic: "Anthropic",
  gemini: "Google Gemini",
  openrouter: "OpenRouter",
  glm: "GLM",
  "glm-cn": "GLM (China)",
  kimi: "Kimi",
  "kimi-coding": "Kimi Coding",
  Claude: "Claude",
  "Claude-cn": "Claude (China)",
  alicode: "AliCode",
  "alicode-intl": "AliCode International",
  groq: "Groq",
  xai: "xAI",
  mistral: "Mistral",
  perplexity: "Perplexity",
  together: "Together AI",
  fireworks: "Fireworks",
  cerebras: "Cerebras",
  cohere: "Cohere",
  nvidia: "NVIDIA",
  nebius: "Nebius",
  siliconflow: "SiliconFlow",
  hyperbolic: "Hyperbolic",
  ollama: "Ollama",
  vertex: "Google Vertex AI",
  "vertex-partner": "Vertex AI Partner",
};
